---
title: "Task19"
author: "Tyler"
date: "11/14/2022"
output: 
  html_document:
   code_folding: "hide"
   keep_md: TRUE
---

```{r}
library(tidyverse)
library(sf)
library(USAboundaries)
library(ggplot2)
library(readr)
library(knitr)
library(tidyverse)
library(dplyr)
library(forcats)
library(downloader)
library(corrplot)
library(ggrepel)
library(sf)
library(maps)
library(readr)
library(remotes)
library(dygraphs)
library(ggsflabel)
library(plotly)
library(gridExtra)
library(leaflet)
```

```{r}
id <- us_counties(states = "ID")
states <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))
```


```{r}
cities <- us_cities()
```


```{r}
topcity <- cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii') %>%
  group_by(state_name) %>%
  arrange(desc(population)) %>%
  slice(1:3)
head(topcity)
```


```{r}
number1 <- topcity %>%
  slice(1:1)
head(number1)

number2 <- topcity %>%
  slice(2:2)

number3 <- topcity %>%
  slice(3:3)
```



```{r}
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = number1,radius = 7,color = "darkblue",stroke = FALSE,fillOpacity = 1,popup = ~city,label = ~population) %>%
  addCircleMarkers(data = number2,radius = 5,color = "blue",stroke = FALSE,fillOpacity = 1,popup = ~city,label = ~population) %>%
  addCircleMarkers(data = number3,radius = 3,color = "lightblue",stroke = FALSE,fillOpacity = 1,popup = ~city,label = ~population)

```

