---
title: "Task20"
author: "Tyler"
date: "11/17/2022"
output: 
 html_document:
   keep_md: TRUE
---

```{r}
library(tidyverse)
library(sf)
library(USAboundaries)
library(ggplot2)
library(readr)
library(knitr)
library(tidyverse)
library(dplyr)
library(forcats)
library(downloader)
library(corrplot)
library(ggrepel)
library(sf)
library(maps)
library(readr)
library(remotes)
library(dygraphs)
library(ggsflabel)
library(plotly)
library(gridExtra)
library(gganimate)
```
#THis data came from task 7
```{r}
download.file("https://raw.githubusercontent.com/hadley/r4ds/master/data/heights.csv", "heights")

Height <- read_csv("heights")

Height
```

```{r}
HeightEd <- Height %>%
  mutate(ed = as.factor(ed)) %>%
  mutate(ed = fct_recode(ed,
                         "primary" = "3",
                         "primary" = "4",
                         "primary" = "5",
                         "primary" = "6",
                         "secondary" = "7",
                         "secondary" = "8",
                         "secondary" = "9",
                         "secondary" = "10",
                         "secondary" = "11",
                         "highschoolgrad" = "12",
                         "associates" = "13",
                         "associates" = "14",
                         "associates" = "15",
                         "bachelors" =  "16",
                         "mastersdoctorate" = "17",
                         "mastersdoctorate" = "18"))

```

```{r}
HeightEd1 <- HeightEd %>%
  group_by(race) %>%
  count(ed)

HeightEd1

```

```{r}
ggplot(HeightEd1, mapping=aes(ed,n, fill=race ))+
  geom_bar(stat="identity", position = "dodge")+
  labs(title="Race effects education",x="Education",y="Number")+
    theme_bw()+
  transition_states(race, transition_length=2, state_length=1)+
  ease_aes('sine-in-out')
anim_save("animated-barplot-hieght.gif")
  
```



